[theme]
base = "light"
primaryColor = "#0D9488"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#142D42"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
